In [3]:
#array() creates an array from list or tupples
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
a = np.array([[1,2,3],[3,4,5],[6,7,8]])
print(a)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [11]:
#arrange() creates an array of evenly spaced values
import numpy as np
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [12]:
import numpy as np
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [17]:
import numpy as np
a = np.arange(5,10,dtype = "complex")
print(a)

[5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]
